# /etc/sysctl.d/99-l3-overlay.conf
#net.core.rmem_max     = 33554432   # максимум RX сокета; 32 MiB
#net.core.wmem_max     = 33554432   # максимум TX сокета; 32 MiB
#net.core.rmem_default = 8388608    # дефолт RX сокета; 8 MiB
#net.core.wmem_default = 8388608    # дефолт TX сокета; 8 MiB

#net.ipv4.udp_rmem_min = 262144     # минимальный RX для UDP; 256 KiB
#net.ipv4.udp_wmem_min = 262144     # минимальный TX для UDP; 256 KiB


# настройки TUN-интерфейса
[tun]
name       = "tun0"             # имя интерфейса TUN; "tun0"
addr       = "10.10.0.2/24"     # IPv4/CIDR адрес TUN; "10.10.0.1/24"
link_mtu   = 1400               # MTU интерфейса TUN в ядре; 9000 под джамбо-кадры
add_route  = true               # добавить маршрут своей подсети addr в TUN; true=да
#gray_routes = [                 # дополнительные "серые" подсети, которые гнать в TUN
#  "10.20.0.0/16",               # пример 1
#  "10.30.0.0/24"                # пример 2
#]
mtu        = 1400               # размер пользовательского буфера IP; должен быть >= link_mtu

# [transport] — сетевой транспорт QUIC поверх UDP
[transport]
listen     = "0.0.0.0:5555"      # локальный UDP-адрес сервера; порт 5555
alpn       = "go-l3-overlay"     # идентификатор ALPN; должен совпадать у всех узлов
insecure   = true                # клиент: пропуск проверки TLS-сертификата; true для self-signed
streams    = 4                   # число клиентских стримов на peer; 4
udp_rbuf   = 16777216            # размер UDP RX буфера сокета; 16 MiB (≈ достаточен до ~100 ms на 1G)
udp_wbuf   = 16777216            # размер UDP TX буфера сокета; 16 MiB (симметрично)
idle       = "10m"               # MaxIdleTimeout соединения; 10 минут
keepalive  = "25s"               # период keepalive; 25 секунд; "0" отключает

# путь к мэппингу "серый IPv4 → белый host:port"
[map]
path = "peers.toml"             # файл мэппинга; абсолютный путь

#  микробатч пакетов перед отправкой
[batch]
bytes = 131072                   # микробатч 128 KiB ≈ MTU(9K), не раздувает задержку

# [log] — уровень логов
[log]
level = "info"                  # уровень: debug|info|warn|error


